---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggmap)
library(forcats)

library(maptools)
library(maps)



library(ggplot2)
library(dplyr)
require(maps)
require(viridis)
theme_set(
  theme_void()
)

```


```{r}
city_data <- read.csv2("plotting_full_upd.csv")
#write_csv2(city_data, "plotting.csv")

```

```{r}
y_coord <-city_data$lat
x_coord <-city_data$lng
world_map <- map_data("world")
mapWorld <- borders("world", colour="lightgray", fill="lightgray") # create a layer of borders 
```


```{r}
ggplot() +  mapWorld + geom_point(aes(x_coord, y_coord, color = factor(city_data$color), shape=factor(city_data$clust3)), size=4, stroke = 2, alpha = 0.7) +
  labs(color = "Семантическая\nкластеризация", shape = "Макроэкономическая\nкластеризация") +
  scale_color_manual(labels = c("1", "2", "3", "4", "5", "6", "7", "8", "9","10", "11"),
                     values = c("#D01702", "#54BD01", "#0088AE", "#E66E6E", "#E10291", "#00E1E1", "#00A5E1", "#E19239", "#FF69B4", "#008080")) 

# in geompoint it's said that coloring will be based on the 'color' variable because it represents the sematic clustering
# later scale_color_manual allowa to add user colors and labels (was needed here) for each cluster


#+ theme(legend.position="none")  #-- to turn off legend
#ggsave("3cluster_R.png", plot = last_plot())
```

